server:
  host: "localhost"
  port: "8080"
database:
  host: "localhost"
  port: 5432
  user: "billing_user"
  password: "yoursecurepassword"
  dbname: "billing_db"
  sslmode: "disable" # or "require", "verify-full", etc.
  maxRetries: 3
logLevel: "info"
